### ISSUE TITLE
Remove the node_modules from repo

### ISSUE THREAD

**Issue by ABIDULLAH786** [Mridul20/Certify#1]
Having node_modules in repository is not a good thing it consumes resources and also take time to clone repository

![image](https://user-images.githubusercontent.com/67856787/177090061-2ce4a4eb-f903-4f95-a81d-219a57d6c798.png)

**Comment by Mridul20** [comment]
Wait will update the repo

**Comment by Mridul20** [comment]
removed node_modules and added gitignore
remember to run npm install after cloning the repo.
